name: Lokalise Key Push
description: 'Pushes new translations keys to Lokalise'
branding:
  icon: arrow-up-circle
  color: purple
inputs:
  api-token:
    description: API token
    required: true
  project-id:
    description: The project ID
    required: true
  directory:
    description: The directory to find language files
    required: true
  format:
    description: The file format to parse. (json, properties)
    required: true
  platform:
    description: The Lokalise platform to sync
    required: true
  filename:
    description: The Lokalise filename to use on new keys
    required: true
  use-filepath:
    description: Use full filepath as a filename
    required: false
  ref:
    description: Branch ref for tagging
    required: false
  target-ref:
    description: Branch to compare with
    required: true
  repository:
    description: github.repository
    required: true
  repo-token:
    description: Token for github requests (used for read only - contents, commits, compare)
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
